#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  Flow:
    security:
      enable: TRUE
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
    resource:
      storages:
        defaultPersistentResourcesStorage:
          storage: 'TYPO3\Flow\Resource\Storage\WritableFileSystemStorage'
          storageOptions:
            path: '%FLOW_PATH_DATA%Persistent/Resources/'
    session:
      inactivityTimeout: 86400
    i18n:
      defaultLocale: ua
      fallbackRule:
        strict: FALSE
        order: [ua,en]
Incvisio:
  LostFound:
    strategies:
      Facebook:
        app_id: '823254257800608'
        app_secret: '9ab9009d70cd972988e71a59a104a1cf'
        scope: 'public_profile,email' # optional
        redirect_uri: 'http://lostfound.armtechnologies.com/incvisio.lostfound/login/social'
      Vk:
        app_id: '5311928'
        app_secret: 'nYCqcR7og8fgskJVEfbR'
        redirect_uri: 'http://lostfound.armtechnologies.com/incvisio.lostfound/login/social?social=vk'
      Twitter:
        app_id: 'C2U3XG7PpdsxpHbPYUCBFplpy'
        app_secret: 'WQ9rVRb9QJ2O56dElNriw6O2CshAxpBbDsSMSxikvz1rGQzGEr'
        redirect_uri: 'http://lostfound.armtechnologies.com/incvisio.lostfound/login/social?social=twitter'
      Google:
        app_id: '198232667061-mvh7afunidgg5cdii0e9a23lfjjmms43.apps.googleusercontent.com'
        app_secret: 'bJXA3LfFTTGm02V57Dt5yXth'
        redirect_uri: 'http://lostfound.armtechnologies.com/incvisio.lostfound/login/social?social=googleplus'
      Crop:
        comment: 200
      Liqpay:
        signature: Zh8G/lTg9FLGH5UKYocuuCC0LcA=
        data: eyJ2ZXJzaW9uIjozLCJhY3Rpb24iOiJwYXlkb25hdGUiLCJwdWJsaWNfa2V5IjoiaTEyNDg1NTYzNDM0IiwiYW1vdW50IjoiNSIsImN1cnJlbmN5IjoiVUFIIiwiZGVzY3JpcHRpb24iOiLQnNC+0Lkg0YLQvtCy0LDRgCIsInR5cGUiOiJkb25hdGUiLCJsYW5ndWFnZSI6ImVuIn0=